### ISSUE TITLE
'sass' not recognized as an internal or external command

### ISSUE THREAD

**Issue by AlexanderBech** [bnlucas/SassBuilder#1]
I installed SassBuilder, but when saving my .scss file I get the following error in Console. (Translated to english):

'sass' not recognized as an internal or external command

**Comment by bnlucas** [comment]
Closing this issue.

**Comment by karannRTL** [comment]
really you saved my life.
I was really searching for this issue from 4 hours.
really buddy thank you sooooooo much.
