### ISSUE TITLE
Zero length field name in format

### ISSUE THREAD

**Issue by random6886** [bnlucas/SassBuilder#15]
I was able to install SassBuilder to sublime text 2. I'm running python 2.7 on OSX.

When I go to save the .scss file, I get the "ValueError" and I'm not too sure what's causing it.

    SassBuilder started.
    Traceback (most recent call last):
      File "./sublime_plugin.py", line 190, in on_post_save
      File "./sublime_plugin.py", line 154, in run_timed_function
      File "./sublime_plugin.py", line 189, in <lambda>
      File "./SassBuilder.py", line 163, in on_post_save
      File "./SassBuilder.py", line 132, in compile_sass
    ValueError: zero length field name in format

    {
        "project_path": "./css",
        "output_path": "./css",
	    "options": {
		    "cache":         true,
		    "debug":         true,
		    "line-comments": true,
		    "line-numbers":  true,
		    "style":         "nested"
	    }
    }

I have also tried it with hard coded paths. When I remove the attribute "output_path", it says that output_path is missing, so I presume there is something I'm missing.

**Comment by samnabi** [comment]
I get the same issue.

Here's my `.sassbuilder-config.json`

```
{  
    "project_path": "../",
    "output_path": "../css",  
    "options": {  
        "cache":         true,  
        "debug":         false,  
        "line-comments": false,  
        "line-numbers":  false,  
        "style":         "compressed"
    }  
}  
```

Here's my file structure
```
project/
    assets/
        css/
        scss/
            _partial.scss
            styles.scss
            .sassbuilder-config.json
```

**Comment by tookiez** [comment]
Same as you. I tried different alternative, but no one worked.

.sassbuilder-config.json

```
{
	"output_path": "../css/main.css",
	"options": {
        "cache":         true, 
        "debug":         false,
        "line-comments": true,
        "line-numbers":  true,
		"style":         "compressed"
	}
}
```
My file structure

```
project/
    css/
        animation.css
        main.css
    scss/
        main.scss
        .sassbuilder-config.json
```

**Comment by dietcode** [comment]
I'm getting the same issue too

**Comment by mspriyakk** [comment]
did anyone fix their issue?

**Comment by samnabi** [comment]
I switched to a different plugin: https://github.com/jaumefontal/SASS-Build-SublimeText2

**Comment by HunterJoe** [comment]
This appears to have something to do with the Python version installed on the user's system versus the way the method call is syntaxed. I don't know Python, but a quick google search indicates that the way the author has implemented the method syntax works only on certain versions of python and not on others. I am running version 2.7.10 with ST 2. The syntax used is supposed to work in 3.1 if using Python 3, and 2.7 if using version 2, apparently. I will look into this more and get back to it.

**Comment by bnlucas** [comment]
Updated the string.format() calls.
