### ISSUE TITLE
Help! Packages/Javascript/JSON.tmLanguage error

### ISSUE THREAD

**Issue by for3v3r4u** [bnlucas/SassBuilder#25]
Can someone explain me how can I make this work??
I added a repository, I found the SassBuilder and I install it, from the project bar I've made a right click on the folder and click on Sass config file and was creating the file automatically (the path it's taken auto) but when I write code I receive an error "b"'sass' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
error: SassBuilder: Hit 'ctrl+`' to see errors." 

Please help me! I'm quite new with this

**Comment by borisyordanov** [comment]
Did you fix this error?

**Comment by kayvine** [comment]
Any solution for this?

**Comment by for3v3r4u** [comment]
not that I know of. I quit this one long time ago and looked in other options.
