### ISSUE TITLE
Error when saving scss file in Windows 10 x64

### ISSUE THREAD

**Issue by rjquery** [bnlucas/SassBuilder#30]
> SassBuilder started.
> b"'sass' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
> error: SassBuilder: Hit 'ctrl+`' to see errors.

Latest sublime version.

**Comment by ddorstijn** [comment]
Install sass
You can do this by installing Ruby. More detailed explanation:
http://sass-lang.com/install

**Comment by rjquery** [comment]
Thank you
